/**
 * Target Company Jobs Agent — stub
 *
 * This agent previously scraped career pages (Greenhouse/Lever ATS, JSON-LD, HTML)
 * and BioSpace to find open roles at BD-pipeline companies. All non-LinkedIn signal
 * creation paths have been removed.
 *
 * Stale job signals are now generated exclusively by staleJobTracker.js via the
 * LinkedIn guest API (runs nightly via GitHub Actions). target_company_job signals
 * from career page scraping have been removed; stale_job_posting signals from
 * BioSpace have been removed.
 *
 * This stub preserves the agent_runs log entry and the return schema expected by
 * the orchestrator without performing any work.
 */

import { supabase } from '../lib/supabase.js'

export async function run() {
  const { data: runEntry } = await supabase
    .from('agent_runs')
    .insert({
      agent_name:  'target-company-jobs-agent',
      status:      'completed',
      started_at:  new Date().toISOString(),
      completed_at: new Date().toISOString(),
      signals_found: 0,
      run_detail: {
        note: 'Non-LinkedIn sources removed. Stale job signals now generated by staleJobTracker via GitHub Actions.',
      },
    })
    .select()
    .single()

  console.log('[targetCompanyJobs] Stub run — non-LinkedIn sources removed, stale jobs handled by GitHub Actions')
  return { signalsFound: 0, companiesChecked: 0 }
}
